/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    properties: Property;
    pages: Page;
    media: Media;
    activity: Activity;
    'email-queue': EmailQueue;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    activity: ActivitySelect<false> | ActivitySelect<true>;
    'email-queue': EmailQueueSelect<false> | EmailQueueSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The user's full name, shown in the header and on their profile.
   */
  name: string;
  /**
   * The user's role on the Iris platform.
   */
  roles: ('super-admin' | 'user')[];
  /**
   * Protect your account with a time-based code from an authenticator app.
   */
  mfa?: {
    enabled?: boolean | null;
    secret?: string | null;
    pendingSecret?: string | null;
    backupCodes?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Iris subscription state for this account.
   */
  billing: {
    /**
     * Current Stripe subscription status. 'none' = no subscription on record.
     */
    subscriptionStatus: 'none' | 'trialing' | 'active' | 'past_due' | 'canceled';
    /**
     * Stripe Customer ID (cus_…). The durable link to Stripe — set once, then keyed on.
     */
    stripeCustomerId?: string | null;
    /**
     * Stripe Subscription ID (sub_…).
     */
    stripeSubscriptionId?: string | null;
    /**
     * Stripe Price ID (price_…) the account is subscribed to — identifies the plan.
     */
    priceId?: string | null;
    /**
     * When the current paid period ends (from Stripe).
     */
    currentPeriodEnd?: string | null;
    /**
     * Set when a payment fails (status past_due). Content keeps serving until this time, then access is cut off.
     */
    gracePeriodEndsAt?: string | null;
  };
  properties?:
    | {
        property: number | Property;
        roles: ('property-admin' | 'property-editor' | 'property-viewer')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Each Property is a website Ravision Tech manages. It's users and pages are scoped to it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  name: string;
  /**
   * Used in URLs to identify this property's site (e.g. /acme).
   */
  slug: string;
  /**
   * Optional custom domain for this property (for domain-based routing).
   */
  domain?: string | null;
  /**
   * If enabled, this property's published pages are publicly readable without login.
   */
  allowPublicRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  property?: (number | null) | Property;
  title: string;
  /**
   * URL path for this page within the property's site (e.g. 'about').
   */
  slug: string;
  /**
   * Change the page by editing the content that appears on it.
   */
  content?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            backgroundImage?: (number | null) | Media;
            cta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            media?: (number | null) | Media;
            mediaPosition?: ('right' | 'left') | null;
            link?: {
              label?: string | null;
              url?: string | null;
              newTab?: boolean | null;
              style?: ('primary' | 'secondary' | 'text') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            columns?: ('2' | '3' | '4') | null;
            items?:
              | {
                  icon?: (number | null) | Media;
                  title: string;
                  description?: string | null;
                  /**
                   * Optional link for this feature.
                   */
                  link?: {
                    label?: string | null;
                    url?: string | null;
                    newTab?: boolean | null;
                    style?: ('primary' | 'secondary' | 'text') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  /**
                   * e.g. "10k+", "98%", "$2M"
                   */
                  value: string;
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  quote: string;
                  authorName: string;
                  /**
                   * Role and/or company.
                   */
                  authorTitle?: string | null;
                  avatar?: (number | null) | Media;
                  /**
                   * Optional 1–5 star rating.
                   */
                  rating?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            /**
             * e.g. "Trusted by teams at"
             */
            heading?: string | null;
            logos?:
              | {
                  image: number | Media;
                  /**
                   * Used as alt text.
                   */
                  name?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoCloud';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            tiers?:
              | {
                  name: string;
                  /**
                   * e.g. "$29", "Free", "Contact us"
                   */
                  price: string;
                  /**
                   * e.g. "/month", "/year"
                   */
                  period?: string | null;
                  description?: string | null;
                  features?:
                    | {
                        feature: string;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * Button for this tier.
                   */
                  link?: {
                    label?: string | null;
                    url?: string | null;
                    newTab?: boolean | null;
                    style?: ('primary' | 'secondary' | 'text') | null;
                  };
                  highlighted?: boolean | null;
                  /**
                   * Optional ribbon, e.g. "Most popular".
                   */
                  badge?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading?: string | null;
            layout?: ('grid' | 'masonry' | 'carousel') | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            /**
             * YouTube or Vimeo URL. Leave blank to use an uploaded file.
             */
            url?: string | null;
            /**
             * Optional self-hosted video file.
             */
            file?: (number | null) | Media;
            /**
             * Optional thumbnail/poster image.
             */
            poster?: (number | null) | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            speed?: ('slow' | 'medium' | 'fast') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'marquee';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            members?:
              | {
                  photo?: (number | null) | Media;
                  name: string;
                  role?: string | null;
                  bio?: string | null;
                  socials?:
                    | {
                        platform?:
                          | (
                              | 'instagram'
                              | 'linkedin'
                              | 'twitter'
                              | 'facebook'
                              | 'youtube'
                              | 'github'
                              | 'tiktok'
                              | 'website'
                            )
                          | null;
                        url: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            heading?: string | null;
            text?: string | null;
            email?: string | null;
            phone?: string | null;
            address?: string | null;
            /**
             * Optional Google Maps embed URL.
             */
            mapEmbedUrl?: string | null;
            showForm?: boolean | null;
            socials?:
              | {
                  platform?:
                    | ('instagram' | 'linkedin' | 'twitter' | 'facebook' | 'youtube' | 'github' | 'tiktok' | 'website')
                    | null;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            heading: string;
            text?: string | null;
            backgroundImage?: (number | null) | Media;
            buttons?:
              | {
                  label?: string | null;
                  url?: string | null;
                  newTab?: boolean | null;
                  style?: ('primary' | 'secondary' | 'text') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  property?: (number | null) | Property;
  /**
   * Describe the image for accessibility and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Read-only log of system events — emails sent, billing changes, account activity.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity".
 */
export interface Activity {
  id: number;
  /**
   * Machine event key, e.g. email.sent, subscription.active.
   */
  action: string;
  /**
   * Human-readable summary of what happened.
   */
  message: string;
  /**
   * The account this event relates to, if any.
   */
  user?: (number | null) | User;
  /**
   * Extra structured detail (recipient, amount, ids, …).
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Emails awaiting retry after a send failure (e.g. rate limits).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-queue".
 */
export interface EmailQueue {
  id: number;
  /**
   * Recipient address(es).
   */
  to: string;
  /**
   * Subject line, for readability.
   */
  subject?: string | null;
  status: 'pending' | 'failed';
  /**
   * How many send attempts have been made.
   */
  attempts: number;
  /**
   * When the retrier should next try this message.
   */
  nextAttemptAt?: string | null;
  /**
   * The most recent send error.
   */
  lastError?: string | null;
  /**
   * Serialized message payload used to resend (attachments are base64).
   */
  message:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'activity';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'email-queue';
        value: number | EmailQueue;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  mfa?:
    | T
    | {
        enabled?: T;
        secret?: T;
        pendingSecret?: T;
        backupCodes?: T;
      };
  billing?:
    | T
    | {
        subscriptionStatus?: T;
        stripeCustomerId?: T;
        stripeSubscriptionId?: T;
        priceId?: T;
        currentPeriodEnd?: T;
        gracePeriodEndsAt?: T;
      };
  properties?:
    | T
    | {
        property?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  allowPublicRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  property?: T;
  title?: T;
  slug?: T;
  content?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              heading?: T;
              content?: T;
              media?: T;
              mediaPosition?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              subheading?: T;
              columns?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                          style?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorTitle?: T;
                    avatar?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoCloud?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    image?: T;
                    name?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              heading?: T;
              subheading?: T;
              tiers?:
                | T
                | {
                    name?: T;
                    price?: T;
                    period?: T;
                    description?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                          style?: T;
                        };
                    highlighted?: T;
                    badge?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              layout?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              heading?: T;
              url?: T;
              file?: T;
              poster?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        marquee?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              speed?: T;
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              heading?: T;
              subheading?: T;
              members?:
                | T
                | {
                    photo?: T;
                    name?: T;
                    role?: T;
                    bio?: T;
                    socials?:
                      | T
                      | {
                          platform?: T;
                          url?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              heading?: T;
              text?: T;
              email?: T;
              phone?: T;
              address?: T;
              mapEmbedUrl?: T;
              showForm?: T;
              socials?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              text?: T;
              backgroundImage?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  property?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_select".
 */
export interface ActivitySelect<T extends boolean = true> {
  action?: T;
  message?: T;
  user?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-queue_select".
 */
export interface EmailQueueSelect<T extends boolean = true> {
  to?: T;
  subject?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  lastError?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


